version: "1.0"

services:
  simula-plus-api:
    container_name: simula-plus-api
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    restart: unless-stopped
